[package]
name = "rcmd_client"
version = "0.1.0"
edition = "2018"

[dependencies]
rcmd_data = {path = "../rcmd_data"}
reqwest = { version = "0.11", features = ["blocking", "json", "rustls-tls-manual-roots"] }
structopt = "0.3"