[package]
edition = "2018"
name = "rcmd_server"
version = "0.1.0"

[dependencies]
rcmd_lib = {path = "../rcmd_lib"}
# only latest unpublished Rocket includes mTLS support
rocket = {git = "https://github.com/SergioBenitez/Rocket", rev = "8cae077ba1d54b", features = ["json", "tls", "mtls"]}