[package]
edition = "2018"
name = "rcmd_server"
version = "0.1.0"

[dependencies]
rcmd_lib = {path = "../rcmd_lib"}
rocket = {git = "https://github.com/SergioBenitez/Rocket", branch = "master", features = ["json", "tls", "mtls"]}